# permissions for end users to edit zyroncontainersecurities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zyron-containersecurity
    app.kubernetes.io/managed-by: kustomize
  name: editor-role
rules:
- apiGroups:
  - container-security.emprovise.com
  resources:
  - zyroncontainersecurities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - container-security.emprovise.com
  resources:
  - zyroncontainersecurities/status
  verbs:
  - get
